name: verify

on:
  push:

jobs:
  library:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Prepare Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "8"
      - name: Prepare Codebase
        uses: actions/checkout@v2
      - name: Prepare CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "java"
      - name: Restore Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Execute Tests
        run: ./mvnw clean verify
      - name: Execute CodeQL Analysis
        uses: github/codeql-action/analyze@v1
